---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Static website hosting based on S3 bucket
Parameters:
  S3BucketName:
    Description: S3 bucket name used for static website hosting
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # the bucket has the same name as domain
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublicAccessPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
      Bucket: !Ref S3Bucket
Outputs:
  S3BucketName:
    Description: The name of the generated S3 bucket
    Value: !Ref S3BucketName
  EndpointURL:
    Description: URL for website hosted on S3
    Value: !GetAtt [S3Bucket, WebsiteURL]
... 
